import React from "react";
import 'antd/dist/antd.css';
import { Layout, Menu, Breadcrumb, Icon, Anchor } from 'antd';
import { PageHeader, Dropdown, Button, Tag, Typography, Row } from 'antd';

const { Paragraph } = Typography;
const { Header, Content, Footer, Sider } = Layout;

// The web components generated by DSL will be appended to the end of this file


